apiVersion: v2
name: version-notifier
version: 0.7.3
appVersion: |-
  0.7.6
description: "This chart was made to keep every team member updated regarding version of packages charts images and basically whatever is available as a github release (package)"
maintainers:
  - name: yuval press
    email: yuvalpress@gmail.com
